### ISSUE TITLE
Examine the inventory and estimate how many kits we can provide

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#11]

**Comment by PeterJCLaw** [comment]
Just in case you're not aware of it, the inventory tooling has a [query language](https://srtools.readthedocs.io/en/latest/inventory/index.html#making-queries) which you might find useful for this. I've found that the language can feel tricky to get going with unfortunately (thoughts on how to fix that are definitely welcome!) but is very useful once you've got the hang of it.

If it would be helpful I can also share the notes I have from SR2019 around what kit was in what state at the start (I put together a spreadsheet which I used for calculations and input the data from the inventory manually), and I'd be happy to help you get going with the inventory tooling.

From memory we're most likely to be short of power boards (I think we had about one spare during SR2019), though there are quite a few which only need minor fixes to get them back to being working.

**Comment by kierdavis** [comment]
This happened; we're confident we can support up to 40 kits this competition year.
