### ISSUE TITLE
Trial using Github projects to manage action points and lead discussion in meetings

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#18]

**Comment by kierdavis** [comment]
I've made a project and organised all our outstanding action point issues. I think we should trial using it as a prompt in our next meeting instead of an agenda document.

**Comment by rgilton** [comment]
Thanks.  Perhaps some definition of what the columns mean would be good.  Here is an attempt at that:

 * "Ideas": Ideas that committee members have had and would like to cover at some point in the future.  Items in this list are not in priority order, as committee members can just chuck stuff into this list whenever they feel like it.
 * "Requires discussion": A prioritised list (i.e. things at the top of the list will be covered first) of things that are to be discussed in future meetings.
 *  "Requires action": Stuff that can now be done by committee members without further committee discussion.
 * "Done": Stuff that is now complete.

A few things I can see that need some tweaking:

 1. I think there is a missing column called "Doing".  This would be where items sit while they are being performed.  So an item flows from Ideas -> Requires discussion -> Requires action -> Doing -> Done.
 2. We need to work out what the process is for how stuff transitions from "ideas" to "requires discussion".

**Comment by kierdavis** [comment]
I'm just in the process of writing an email explaining how I've set this up; apologies for doing these things somewhat out-of-order :)

Regarding the "doing" column, my intention was for the "requires action" column to include both tasks that are ready to start and tasks that are in progress, because I couldn't think of a good reason to separate the two. I think it makes more sense to use assignments to track what's currently being worked on: someone being assigned to a task implies that they're intending to work on the task in the near future. I'm happy to add a "doing" column if you think it would be useful.

This did make me realise that there should probably be a "blocked" column, which I've now created.

I don't have a plan for how to transition things out of the "ideas" state yet - maybe we could just pull them into "requires discussion" if they become relevant or if there's not much else to discuss.

**Comment by rgilton** [comment]
Ah, sorry for jumping in while you were still working on it.  I must have just happened to have looked at what was going on at just the wrong time...

I think it would be good to have a "doing" column, as it makes it clear when something is actually being worked on.

**Comment by kierdavis** [comment]
It felt like the trial meeting went well, and we got good feedback from everyone involved in the meeting. I'm going to close this and propose we formalise the process (#22).
