### ISSUE TITLE
Email competition team committee

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#2]

**Comment by RealOrangeOne** [comment]
https://github.com/srobo/competition-team-minutes/issues/118 is likely relevant to your interests!

**Comment by RealOrangeOne** [comment]
I believe this is covered by the meeting the trustees are planning to have in the next couple weeks with both teams present?

> we are keen to have a meeting to make sure that you are all happy with the split of responsibilities between the two teams and discuss any areas of concern. Also, we need to be sure that there is nothing major missing (that might not get done)!

**Comment by trickeydan** [comment]
> I believe this is covered by the meeting the trustees are planning to have in the next couple weeks with both teams present?

Partially. We may be able to cover the rest of it over email.

**Comment by kierdavis** [comment]
I think we should put this on hold until after we've met with the trustees and CTC.

**Comment by kierdavis** [comment]
Kickstart is the only critical thing that requires interaction between the competition and kit teams right now, and that's being handled out-of-band. Everything else can be covered in the trustee meeting.
