### ISSUE TITLE
Update odroid overlay for SR2020

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#26]

**Comment by rgilton** [comment]
I have enquired with the comp team about what game we are implementing, and when we know it's actually fixed: https://github.com/srobo/rules/pull/30#issuecomment-537639840

**Comment by rgilton** [comment]
Ok, dug around to find where the repositories relating to this are:

 Repository         | Legacy                                                            | Github                                     
 -------------------|-------------------------------------------------------------------|--------------------------------------------
 herdsman           | https://www.studentrobotics.org/cgit/brain/herdsman.git/          | https://github.com/srobo/brain-herdsman    
 odroid/setup       | https://www.studentrobotics.org/cgit/brain/odroid/setup.git/      | No                                         
 brain/sr-init      | https://www.studentrobotics.org/cgit/brain/specfiles/sr-init.git/ | No                                         
 brain/sr-robot     | https://www.studentrobotics.org/cgit/brain/sr-robot.git/          | https://github.com/srobo/sr-robot          
 brain/wifi         | https://www.studentrobotics.org/cgit/brain/wifi.git/              | No                                         
 brain/zip-packager | https://www.studentrobotics.org/cgit/brain/zip-packager.git/      | https://github.com/srobo/brain-zip-packager
 kernel             | https://www.studentrobotics.org/cgit/brain/odroid/linux-2.6.git/  | No

**Comment by kierdavis** [comment]
FYI, it looks like the game designers are aware of the bad libkoki marker we discussed earlier (https://github.com/srobo/libkoki/issues/5) and are working around it: https://github.com/srobo/rules/blob/60855b41b786fec47371cc8babe3027ebe5b4a98/specs.tex#L20

So I recommend we don't worry about shipping a patch for this competition cycle.

**Comment by rgilton** [comment]
I've created https://github.com/srobo/odroid-image and migrated the original `odroid/setup` repository across to it.  I think this repository will form the hub of the odroid image building etc.

**Comment by kierdavis** [comment]
Relevant: srobo/tasks#365

My opinion is that we should move technical discussion there and leave this issue as a committee-level thing for ensuring it gets tracked in our meetings.

Also something that we didn't think about is updating the docs to match: srobo/tasks#373

**Comment by rgilton** [comment]
Yes, I hadn't planned on this becoming a technical discussion here.  I am creating tasks for things in the relevant repositories (e.g. https://github.com/srobo/odroid-image/issues/1)

**Comment by rgilton** [comment]
I don't seem to be able to make the odroid-image repository public.  Apparently "Organization members can’t change repo visibility."  (Edit: Now resolved.)

**Comment by rgilton** [comment]
I'm going to emit a KTC motion email to get responsibility for sorting the initial shipment of the odroid overlay/sr-robot/zip-packager stuff delegated to myself temporarily.  (Longer term dev/support of it will be dealt with separately later.)

**Comment by rgilton** [comment]
Done.
