### ISSUE TITLE
Propose a motion to refactor how we store/publish minutes

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#30]

**Comment by rgilton** [comment]
Background:  Currently we do not have a definition of what is supposed
to be in the minutes of a meeting, and our minutes so far have
generally been notes from discussions in meetings interlaced with
records of the decisions that have been made.  This makes it difficult
for committee members to sign-off on minutes, as it is not clear
whether they are signing-off on the decisions in the minutes, or the
surrounding notes (... and they would have to re-hash the discussion
to have the minutes modified).  It also makes it difficult to work out
what decisions have been made, as they are mixed up amongst other
statements that have no impact on operations.

Furthermore, the public posting of the notes that are in the minutes
makes it more difficult for committee members to have conversations
about partially-formed ideas with the rest of the committee.  Our
ability as a committee to constructively discuss is hampered by the
need to vet everything we say in a meeting, lest it be misinterpreted
by an arbitrary third-party reading the meeting notes.

Motion: It is proposed that the meeting minutes contain the following
information, and no more:
 - The time and date of the meeting
 - The names of the people present at the meeting
 - A concise and clear description of the motions passed (a.k.a. the
   decisions made) at the meeting.  These may include a short
   background section to include any necessary context for the motion
   to make sense to a committee-member who is referring back to the
   minutes in the future.  Each motion should have the number of votes for/against recorded against it.

**Comment by kierdavis** [comment]
Ack
