### ISSUE TITLE
Check with CT whether any/all of the Kickstart no-shows are still intending to compete

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#33]
KDE, QMC and SOG.

**Comment by rgilton** [comment]
I think the situation is now that Jake will send me the shipping details as and when kits need to be shipped, so this question is probably now not relevant.  Nevertheless I have emailed to confirm.

**Comment by RealOrangeOne** [comment]
The question on whether they're still planning to compete should hopefully be solved by whether they respond with a signed disclaimer.

I'm hoping to get an email re-prompting for that information out this week, so if we don't hear anything by say December, we can start the "Do you still want to compete" processes
