### ISSUE TITLE
Find venue for brainstorming session

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#4]

**Comment by kierdavis** [comment]
This has been scheduled for ~~September~~ October 13th. We still need to find a venue.

**Comment by trickeydan** [comment]
Have updated via email.

**Comment by rgilton** [comment]
@kierdavis Actually _October_ 13th :smile: 

We are going to have this in Southampton.  Just need room booking.

**Comment by trickeydan** [comment]
I have booked `34/5007` on Highfield Campus

https://data.southampton.ac.uk/room/34-5007.html

**Comment by kierdavis** [comment]
(10:00 - 18:00)
