### ISSUE TITLE
Runbook problems

### ISSUE THREAD

**Issue by rgilton** [srobo/kit-team-minutes#45]
Issues with merging vision PR into run book.

**Comment by rgilton** [comment]
Literally our first PR into the runbook has run into problems.  Merge is being blocked by someone not in the CTC (and I have no idea if the CTC has delegated such matters to him).

Possible strategies for getting the vision document up so we can start teams:
 1. Invest time in finding a compromise.
 2. Create separate docs for the KT.

Will enquire at next week's KTC meeting who is actually interested in investing their own time on option 1.

**Comment by RealOrangeOne** [comment]
(Not the place for discussion, I know)

I would be very interested in working towards a compromise in this. Happy to discuss whenever!
