### ISSUE TITLE
Sort out github accounts for brain team

### ISSUE THREAD

**Issue by rgilton** [srobo/kit-team-minutes#49]

**Comment by rgilton** [comment]
@didottyd Please can the following user accounts be added to the SR github organisation?
 - tpoomlmly
 - sersorrel
 - mltnhm

**Comment by RealOrangeOne** [comment]
@rgilton spotted this, I've sent invites to @tpoomlmly and @sersorrel, and added them to the brain team group.

mltnhm was already a member of the org and team.
