### ISSUE TITLE
Create committee subteam and fix repo permissions

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#5]

**Comment by kierdavis** [comment]
* [x] Get permission to create subteams
* [x] Create a subteam for the kit team committee
* [x] Give the KTC admin permission on this repo, and reduce the KT's permission to read

**Comment by trickeydan** [comment]
We need Team Maintainer permissions. I suggest getting it for all of the committee.

@RealOrangeOne may be able to help with this

**Comment by RealOrangeOne** [comment]
GitHub's permissions model is such that either all organisation members can create teams, or only owners can create teams.

In the interest of keeping things organised, and partially PoLP, I highly recommend doing the former.

Giving everyone on the team permission is likely unnecessary, but providing 1 person on the kit team committee (just as the competition team committee has in me) access is likely a good way to handle this! My suggestion would be @rgilton, as chair.

In the short term, if you want me to create any teams / modify any existing permissions, let me know! I've had a look through the permissions and made sure `@srobo/kit-team` has elevated access to the repos they already had access to, just as `@srobo/competition-team` does.

**Comment by trickeydan** [comment]
> GitHub's permissions model is such that either all organisation members can create teams, or only owners can create teams.

https://help.github.com/en/articles/giving-team-maintainer-permissions-to-an-organization-member

> In the interest of keeping things organised, and partially PoLP, I highly recommend doing the former.
> 
> Giving everyone on the team permission is likely unnecessary, but providing 1 person on the kit team committee (just as the competition team committee has in me) access is likely a good way to handle this! My suggestion would be @rgilton, as chair.

I suggest adding someone at this level in addition regardless of my above suggestion. 

> In the short term, if you want me to create any teams / modify any existing permissions, let me know! I've had a look through the permissions and made sure `@srobo/kit-team` has elevated access to the repos they already had access to, just as `@srobo/competition-team` does.

**Comment by RealOrangeOne** [comment]
Interesting, I've never come across team maintainers before. 

This has now been applied to all members of the Kit Team Committee for `@srobo/kit-team` (and Competition Team Committee for `@srobo/competition-team`)

**Comment by kierdavis** [comment]
Thanks @RealOrangeOne!

The "Add a team" button is still unavailable for me though :cry:. Same message as before, "Only owners and team maintainers can create child teams".

**Comment by RealOrangeOne** [comment]
![image](https://user-images.githubusercontent.com/6527489/64001895-bba37100-cb00-11e9-806b-15680426b635.png)

@kierdavis You're definitely a maintainer of the 'Kit Team' team. Are you trying to create child teams of 'Kit Team', or of the root 'Volunteers' group? The latter wouldn't work, but the former definitely should!

**Comment by kierdavis** [comment]
I'm going to https://github.com/orgs/srobo/teams/kit-team, then to the "Teams" tab, and trying to click the "Add a team" button (which is grayed out). I can see myself listed as maintainer in the "Members" tab though, so I'm not sure what's going on here.

**Comment by kierdavis** [comment]
Update: the "Add a team" button now seems to be enabled for me. That might have been a result of me setting my role in the KT team to team maintainer (even though it said it was already set to that), or it might not, I didn't check.

Regardless, I still can't get subteam creation to work - pressing "Add a team" only seems to allow me to move an existing team into the kit team hierarchy.

@RealOrangeOne Please could you either
- create a subteam under Kit Team named Kit Team Committee and add myself, Rob, Tom, Dan and Kajetan as team maintainers, or
- make me an org owner so that I can make this change (and any future changes that the kit team may require) myself?

**Comment by RealOrangeOne** [comment]
> @RealOrangeOne Please could you ... create a subteam under Kit Team named Kit Team Committee and add myself, Rob, Tom, Dan and Kajetan as team maintainers

This is done, and available at https://github.com/orgs/srobo/teams/kit-committee.

>  I still can't get subteam creation to work 


This is, strange. The GitHub UI definitely suggests team maintainers can modify the current group and create child groups:

![image](https://user-images.githubusercontent.com/6527489/64914312-f3d4c180-d746-11e9-9faa-ba2f8e5cbbea.png)

I'm definitely interested in working out why this isn't working. When we're next in the same room I'd very much enjoy poking at this issue! Can someone else on the committee also try and see if they're hitting the same issues?

**Comment by RealOrangeOne** [comment]
> - [ ] Get permission to create subteams
> - [ ] Create a subteam for the kit team committee
> - [ ] Give the KTC admin permission on this repo, and reduce the KT's permission to read

From my understanding of GitHub's settings, all of these should now be implemented:

- A group exists for the kit team, of which the committee members are maintainers. 
- The kit committee group exists as a child of it, and the committee members are also maintainers of that (no idea if that makes a difference, but just in case it's useful!). 
- The kit committee team has admin access to the `kit-team-minutes` repo, and the kit team group (and any future child teams) have read access. (Although I suspect allowing the team to have write access will actually be more useful long term, but that's just me)


And with that, my work here is done :wave: ! (Tag me if i'm needed, obviously, but removing my assignment)

**Comment by kierdavis** [comment]
Awesome, thanks Jake!

It certainly is odd that github doesn't do what it says on the tin here, but :woman_shrugging:
