### ISSUE TITLE
Contact teams who have kit to determine if they want to compete next year

### ISSUE THREAD

**Issue by rgilton** [srobo/kit-team-minutes#66]

**Comment by rgilton** [comment]
Email went out last week.  About to process results.

**Comment by rgilton** [comment]
Turns out that the list that the email went out to was not the up-to-date SR2020 list of teams, as the list of emails for that year was not put in mailchimp :cry:  So I'm now waiting on the contact details for all SR2020 teams from the competition team.

**Comment by rgilton** [comment]
I've now got access to the spreadsheet of SR2020 emails.

**Comment by PeterJCLaw** [comment]
Is this also going to cover SR2019 teams too (https://github.com/srobo/tasks/issues/297)?

**Comment by rgilton** [comment]
Emailed all the SR2020 teams.

**Comment by rgilton** [comment]
Emails bounced from GRD and SMS.  Will follow up with them using alternative methods of comms.

SR2019 teams yet to return kit are CHW and MES -- have emailed them.

**Comment by rgilton** [comment]
* GRD: Original contact retired.  Got new contact details for head of DT & Computing, will contact them soon.
 * SMS: Original contact no longer works at school.  Got callback from new head of CS.  Working with him to sort things out.  For SR2021 he will need the sales bumph sending out to him (I will push this up to trustees once we've sorted out the kit's existence etc with him).
 * CHW: Phoned school.  Original contact still works at school.  Receptionist provoked them.  Awaiting callback.
 * MES: Not done anything yet.

btw, this is a prime example of when I want a private git repository that is not open to (a) the public, and (b) a large number of volunteers.

**Comment by rgilton** [comment]
I've just emailed all of the teams who we still haven't heard back from and aren't being dealt with separately (ABS, CAT, CLY, DCG, JAM, LSS, PSC, RUN, SEN, TPS).

**Comment by rgilton** [comment]
I have passed-on the new contact details for CCR, KEV and SMS to the trustees.

**Comment by rgilton** [comment]
Next chasing of teams who have been sent shipping details will be on the 6th of July.
