### ISSUE TITLE
Investigate setting up issue creation bot

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-team-minutes#8]
The competition team committee's equivalent of this repo has a bot that automatically creates issues corresponding to action points in the meeting minutes. Since we're closely following their model with this repo, we should look into setting that up.

This wasn't action pointed in the meeting since it's not required or urgent, but it would be a good thing to think about.

**Comment by trickeydan** [comment]
Would be interesting to investigate this in CI and use the actual python sdk.

**Comment by RealOrangeOne** [comment]
> a bot that automatically creates issues

This isn't quite correct. The issue creation process is manual, and requires running a script in the repo once the minutes are approved.

I too would be interested in seeing how nicely this could be turned into a CI job, although ensuring the authenticating was scoped properly may be interesting.

**Comment by kierdavis** [comment]
Might not be needed if #18 goes well.

**Comment by kierdavis** [comment]
Github projects makes creating issues super easy, so I don't think this is needed.
