### ISSUE TITLE
Collate ideas for the Pi Hat in a google doc

### ISSUE THREAD

**Issue by raccube** [srobo/kit-team-minutes#82]

**Comment by TomWheal** [comment]
Did a google doc get made for this after I left the meeting?

**Comment by WillB97** [comment]
Not that I've seen.

**Comment by raccube** [comment]
Created a doc [here](https://docs.google.com/document/d/1-PXBXmbwaGq-t2yB7Wgf3JyE-i7i3MyMy2U3GvzneWE/edit), let me know if you don't have access

**Comment by trickeydan** [comment]
I have posted this doc in kit-hardware and general in Slack.
