### ISSUE TITLE
Ask TLC if they bought their own batteries and send them standard shipping instructions

### ISSUE THREAD

**Issue by raccube** [srobo/kit-team-minutes#87]

**Comment by RealOrangeOne** [comment]
I have sent the initial question around whether they have their own batteries.

Where are our standard shipping instructions?

**Comment by trickeydan** [comment]
> Where are our standard shipping instructions?

https://studentrobotics.org/runbook/kit/logistics/transport/packaging/

**Comment by RealOrangeOne** [comment]
TLC have 2 SR batteries.

Their team leader could bring the kit back to us next time they take the ferry to England if we want? Else I can send them some shipping instructions.

**Comment by RealOrangeOne** [comment]
I've sent them the shipping instructions, and they'll bring the battery to us in June/July. The rest will be tracked in https://github.com/srobo/kit-logistics/issues/30
